#!/usr/bin/python

import socket
import sys

#if len(sys.argv) != 2:
#     print "Usage: vrfy.py <username>"
#     sys.exit(0)

# Open our list of SMTP servers
with open(r'smtp_ip_open.txt', 'r') as servers:

		for server in servers:
				ip = server.strip()
				# Create a Socket
				s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
				# Connect to the Server
				print("Connecting to " + ip)
				s.connect(( ip, 25))
				# Receive the banner
				banner = s.recv(1024)
				print banner
				with open(r'user_list.txt', 'r') as users:
						for user in users:
								user = user.strip()
								# VRFY a user
								print("Verifying " + user)
								s.send('VRFY ' + user + '\r\n')
								result = s.recv(1024)
								print("Response: " + result)
				# Close the socket
				s.close()
